### ISSUE TITLE
[Newbie Question] Why wrap in std::unique_ptr?

### ISSUE THREAD

**Issue by codecnotsupported** [ddovod/jet-live#12]
What is the purpose behind using ::make_unique so much?
For example: 

Why
auto live = jet::make_unique<jet::Live>(std::move(listener), config);
Instead of something like.
jet::Live live(listener,config);

Cool project by the way.

**Comment by ddovod** [comment]
Hey! Thank you very much.

Actually there's no any hidden meaning under the `unique_ptr` here, you can create an instance of `Live` class on the stack if you want. In my application I store this instance in the service locator using `unique_ptr`, so I use it here just out of habit, no more.

**Comment by ddovod** [comment]
Looks like it's clear now, closing. Please reopen if you have any questions.
